service: tackleit-backend

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  architecture: x86_64 # Use x86_64 to match the GitHub Actions runner environment
  
  ecr:
    images:
      appimage:
        path: ./ # Build from the Dockerfile in the current directory

  environment:
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_REDIRECT_URI: ${env:GOOGLE_REDIRECT_URI}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}
    RAZORPAY_PRO_PLAN_ID: ${env:RAZORPAY_PRO_PLAN_ID}
    TURNSTILE_SECRET_KEY: ${env:TURNSTILE_SECRET_KEY}
    MAIL_USERNAME: ${env:MAIL_USERNAME}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    MAIL_FROM: ${env:MAIL_FROM}
    MAIL_PORT: ${env:MAIL_PORT}
    MAIL_SERVER: ${env:MAIL_SERVER}
    GOOGLE_SCOPES: ${env:GOOGLE_SCOPES}
    MAIL_FROM_NAME: ${env:MAIL_FROM_NAME}
    MAIL_TLS: ${env:MAIL_TLS}
    MAIL_SSL: ${env:MAIL_SSL}

functions:
  api:
    image: appimage
    timeout: 30 # Increase timeout to 30 seconds
    events:
      - httpApi: '*'

package:
  patterns:
    - 'main.py'
    - 'routes/**'
    - 'services/**'
    - 'database.py'
    - 'email_utils.py'
    - 'models.py'
    - 'utils.py'
    - 'client_secret.json'
    - 'requirements.txt'
    - 'Dockerfile'