name: Scrape Jobs Weekly

on:
  schedule:
    - cron: '0 1 * * 1' # Runs weekly on Monday at 1 AM UTC
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt
        pip install -r backend/requirements.txt


    - name: Clear jobs collection before scraping
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      run: |
        python scraper/clear_jobs.py

    - name: Run scraper scripts
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        ACCENTURE_API_URL: ${{ secrets.ACCENTURE_API_URL }}
        ADOBE_API_HOST: ${{ secrets.ADOBE_API_HOST }}
        ADOBE_API_PATH: ${{ secrets.ADOBE_API_PATH }}
        AMAZON_BASE_URL: ${{ secrets.AMAZON_BASE_URL }}
        AMAZON_SEARCH_URL: ${{ secrets.AMAZON_SEARCH_URL }}
        CAPGEMINI_API_URL: ${{ secrets.CAPGEMINI_API_URL }}
        DELOITTE_API_URL: ${{ secrets.DELOITTE_API_URL }}
        INTEL_API_HOST: ${{ secrets.INTEL_API_HOST }}
        INTEL_API_PATH: ${{ secrets.INTEL_API_PATH }}
        INFOSYS_API_URL: ${{ secrets.INFOSYS_API_URL }}
        NVIDIA_API_HOST: ${{ secrets.NVIDIA_API_HOST }}
        NVIDIA_API_PATH: ${{ secrets.NVIDIA_API_PATH }}
        QUALCOMM_API_URL: ${{ secrets.QUALCOMM_API_URL }}
        TCS_API_URL: ${{ secrets.TCS_API_URL }}
      run: |
        python scraper/accenture_scraper.py
        python scraper/adobe_scraper.py
        python scraper/amazon_scraper.py
        python scraper/capgemini_scraper.py
        python scraper/deloitte_scraper.py
        python scraper/intel_scraper.py
        python scraper/infosys_scraper.py
        python scraper/nvidia_scraper.py
        python scraper/qualcomm_scraper.py
        python scraper/tcs_scraper.py

    - name: Build FAISS embedding index
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python scraper/build_embeddings.py
